apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opensandbox.fullname" . }}-controller-manager
  namespace: {{ include "opensandbox.controllerNamespace" . }}
  labels:
    {{- include "opensandbox.controllerLabels" . | nindent 4 }}
