{{- if .Values.createNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "opensandbox.controllerNamespace" . }}
  labels:
    {{- include "opensandbox.controllerLabels" . | nindent 4 }}
{{- end }}
