{{- if .Values.createNamespaces }}
{{- $serverNs := include "opensandbox.serverNamespace" . }}
{{- if ne $serverNs .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $serverNs }}
  labels:
    {{- include "opensandbox.serverLabels" . | nindent 4 }}
{{- end }}
{{- end }}
