apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensandbox.fullname" . }}-batchsandbox-template
  namespace: {{ include "opensandbox.serverNamespace" . }}
  labels:
    {{- include "opensandbox.serverLabels" . | nindent 4 }}
data:
  batchsandbox-template.yaml: |
    {{- .Values.server.batchsandboxTemplate | nindent 4 }}
