apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opensandbox.fullname" . }}-server
  namespace: {{ include "opensandbox.serverNamespace" . }}
  labels:
    {{- include "opensandbox.serverLabels" . | nindent 4 }}
